syntax = "proto3";

// DESFire profile metadata for credentials known to Link and firmware.
package lastlock.api;

import public "credential_profile_configurations.proto";


// Profile and keys for a credential type.
message DesfireProfile
{
  reserved 1 to 19;

  // Device-facing encrypted credential authentication key material.
  optional bytes encrypted_credential_key = 20;

  // Device-facing encrypted privacy authentication key material.
  optional bytes encrypted_privacy_key = 21;

  // Profile configuration values.
  DesfireProfileConfigurations configurations = 22;
}

// Full profile set to apply to devices.
message DesfireProfileSet
{
  repeated DesfireProfile profiles = 1;
  optional bytes ecp = 2;
}
